name: End-to-end tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Setup pnpm
        run: pnpm config set store-dir ~/.pnpm-store
      - name: Install Turbo
        run: pnpm install turbo --global
      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run tests
        run: turbo test --filter web
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: packages/fan-tests/web/reports
          retention-days: 30
